#!/usr/bin/env python3
"""One-loop MS-bar RG system and benchmark evolution for canonical TP-1.

Model and conventions
---------------------
Gauge group: SM x U(1)_X.  S and chi are complex SM singlets with X charges
3 and 1.  SM fields have X=0; S and chi have hypercharge zero.  The scalar
potential is

  V = mH2 H^dag H + mS2 S^dag S + mc2 chi^dag chi
      + lamH(H^dag H)^2 + lamS(S^dag S)^2 + lamc(chi^dag chi)^2
      + lamHS(H^dag H)(S^dag S) + lamHc(H^dag H)(chi^dag chi)
      + lamSc(S^dag S)(chi^dag chi) + [kappa S^dag chi^3 + h.c.].

The signed quadratic parameters are mH2=-muH^2, mS2=-muS^2, and
mc2=mu_chi^2 relative to the vacuum-audit notation.  The SM fermion sector
keeps third-family Yukawas and neglects CKM mixing.  gY is not GUT normalized.

For two Abelian factors, the covariant derivative uses Q^T G A.  This script
evolves the full real 2x2 coupling matrix G.  The charge-trace matrix is
B=diag(41/6,10/3), so beta_G=G(G^T B G)/(16*pi^2).  Zero mixing is therefore
a one-loop invariant trajectory for the minimal field content, though a
nonzero matching value can be supplied.

The quartic scalar-only terms are independently generated by
scalar_rge_generator.py.  The Abelian gauge tensor coefficients are checked
independently by gauge_rge_tensor_check.py against the general formula of
Luo, Wang, and Xiao, Phys. Rev. D 67, 065019 (2003).
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import numpy as np
from scipy.integrate import solve_ivp
from scipy.optimize import brentq

import scalar_rge_generator as scalar_tensor
import unitarity_matrix


LOOP = 16.0 * math.pi**2
NAMES = (
    "Gyy", "Gyx", "Gxy", "Gxx", "g2", "g3",
    "yt", "yb", "ytau",
    "lamH", "lamS", "lamc", "lamHS", "lamHc", "lamSc", "kappa",
    "mH2", "mS2", "mc2",
)
INDEX = {name: i for i, name in enumerate(NAMES)}


def pack(values: Dict[str, float]) -> np.ndarray:
    return np.array([values[name] for name in NAMES], dtype=float)


def unpack(values: Iterable[float]) -> Dict[str, float]:
    return dict(zip(NAMES, (float(x) for x in values)))


def abelian_invariants(p: Dict[str, float]) -> Dict[str, object]:
    G = np.array([[p["Gyy"], p["Gyx"]], [p["Gxy"], p["Gxx"]]], dtype=float)
    eY = np.array([1.0, 0.0])
    eX = np.array([0.0, 1.0])
    uY = G.T @ eY
    uX = G.T @ eX
    wH = 0.5 * uY
    wS = 3.0 * uX
    wc = uX
    return {
        "G": G,
        "uY": uY,
        "uX": uX,
        "CY": float(uY @ uY),
        "CH": float(wH @ wH),
        "CS": float(wS @ wS),
        "Cc": float(wc @ wc),
        "DHS": float(wH @ wS),
        "DHc": float(wH @ wc),
        "DSc": float(wS @ wc),
    }


def beta_numerator(values: Iterable[float]) -> np.ndarray:
    """Return F such that d(values)/d ln(mu) = F/(16*pi^2)."""
    p = unpack(values)
    inv = abelian_invariants(p)
    G = inv["G"]
    CY, CH, CS, Cc = inv["CY"], inv["CH"], inv["CS"], inv["Cc"]
    DHS, DHc, DSc = inv["DHS"], inv["DHc"], inv["DSc"]

    g2, g3 = p["g2"], p["g3"]
    yt, yb, ytau = p["yt"], p["yb"], p["ytau"]
    lamH, lamS, lamc = p["lamH"], p["lamS"], p["lamc"]
    lamHS, lamHc, lamSc, kappa = p["lamHS"], p["lamHc"], p["lamSc"], p["kappa"]
    mH2, mS2, mc2 = p["mH2"], p["mS2"], p["mc2"]

    # Third-family trace invariants.  First- and second-family Yukawas and CKM
    # mixing are negligible for this illustrative one-loop gate.
    T = 3.0 * yt**2 + 3.0 * yb**2 + ytau**2
    Y4 = 3.0 * yt**4 + 3.0 * yb**4 + ytau**4

    B = np.diag([41.0 / 6.0, 10.0 / 3.0])
    betaG = G @ (G.T @ B @ G)

    out: Dict[str, float] = {
        "Gyy": betaG[0, 0], "Gyx": betaG[0, 1],
        "Gxy": betaG[1, 0], "Gxx": betaG[1, 1],
        "g2": -19.0 * g2**3 / 6.0,
        "g3": -7.0 * g3**3,
        "yt": yt * (1.5 * (yt**2 - yb**2) + T - 17.0 * CY / 12.0 - 9.0 * g2**2 / 4.0 - 8.0 * g3**2),
        "yb": yb * (1.5 * (yb**2 - yt**2) + T - 5.0 * CY / 12.0 - 9.0 * g2**2 / 4.0 - 8.0 * g3**2),
        "ytau": ytau * (1.5 * ytau**2 + T - 15.0 * CY / 4.0 - 9.0 * g2**2 / 4.0),
    }

    out["lamH"] = (
        24.0 * lamH**2 + lamHS**2 + lamHc**2
        + 4.0 * lamH * T - 2.0 * Y4
        - (9.0 * g2**2 + 12.0 * CH) * lamH
        + 9.0 * g2**4 / 8.0 + 3.0 * g2**2 * CH + 6.0 * CH**2
    )
    out["lamS"] = 20.0 * lamS**2 + 2.0 * lamHS**2 + lamSc**2 - 12.0 * CS * lamS + 6.0 * CS**2
    out["lamc"] = 20.0 * lamc**2 + 2.0 * lamHc**2 + lamSc**2 + 18.0 * kappa**2 - 12.0 * Cc * lamc + 6.0 * Cc**2
    out["lamHS"] = (
        12.0 * lamH * lamHS + 8.0 * lamS * lamHS + 4.0 * lamHS**2 + 2.0 * lamHc * lamSc
        + 2.0 * T * lamHS - (4.5 * g2**2 + 6.0 * (CH + CS)) * lamHS + 12.0 * DHS**2
    )
    out["lamHc"] = (
        12.0 * lamH * lamHc + 8.0 * lamc * lamHc + 4.0 * lamHc**2 + 2.0 * lamHS * lamSc
        + 2.0 * T * lamHc - (4.5 * g2**2 + 6.0 * (CH + Cc)) * lamHc + 12.0 * DHc**2
    )
    out["lamSc"] = (
        8.0 * lamS * lamSc + 8.0 * lamc * lamSc + 4.0 * lamSc**2 + 4.0 * lamHS * lamHc + 36.0 * kappa**2
        - 6.0 * (CS + Cc) * lamSc + 12.0 * DSc**2
    )
    out["kappa"] = kappa * (12.0 * lamc + 6.0 * lamSc - 3.0 * (CS + 3.0 * Cc))

    out["mH2"] = (
        mH2 * (12.0 * lamH + 2.0 * T - 4.5 * g2**2 - 6.0 * CH)
        + 2.0 * lamHS * mS2 + 2.0 * lamHc * mc2
    )
    out["mS2"] = mS2 * (8.0 * lamS - 6.0 * CS) + 4.0 * lamHS * mH2 + 2.0 * lamSc * mc2
    out["mc2"] = mc2 * (8.0 * lamc - 6.0 * Cc) + 4.0 * lamHc * mH2 + 2.0 * lamSc * mS2
    return pack(out)


def beta(log_mu: float, values: np.ndarray) -> np.ndarray:
    del log_mu
    return beta_numerator(values) / LOOP


def exact_bfb_margin(couplings: Dict[str, float]) -> Tuple[bool, float, float]:
    """Algebraic candidate evaluation of the exact radial BFB reduction."""
    h, s, c = couplings["lamH"], couplings["lamS"], couplings["lamc"]
    hs, hc, sc, k = couplings["lamHS"], couplings["lamHc"], couplings["lamSc"], abs(couplings["kappa"])
    if min(h, s, c) <= 0.0:
        return False, min(h, s, c), 0.0
    boundary = hs + 2.0 * math.sqrt(h * s)
    if boundary <= 0.0:
        return False, boundary, math.inf

    candidates = {0.0}
    if hs != 0.0 and -hc / hs > 0.0:
        candidates.add(math.sqrt(-hc / hs))

    # P branch derivative and the B<0 Schur-complement branch derivative.
    polys = [
        (4.0 * s, 0.0, 2.0 * sc, -2.0 * k, False),
        (4.0 * (s - hs**2 / (4.0 * h)), 0.0,
         2.0 * (sc - hs * hc / (2.0 * h)), -2.0 * k, True),
    ]
    for a3, a2, a1, a0, schur in polys:
        roots = np.roots([a3, a2, a1, a0]) if abs(a3) > 1e-15 else np.roots([a2, a1, a0])
        for root in roots:
            if abs(root.imag) < 1e-9 and root.real >= 0.0:
                t = float(root.real)
                Bval = hs * t * t + hc
                if (Bval < 0.0) == schur:
                    candidates.add(t)

    best = (math.inf, 0.0)
    for t in candidates:
        P = s * t**4 + sc * t*t - 2.0 * k * t + c
        Bval = hs * t*t + hc
        R = P if Bval >= 0.0 else P - Bval**2 / (4.0 * h)
        if R < best[0]:
            best = (R, t)

    # Positive asymptotic coefficient in whichever branch applies for large t.
    asym = s if hs >= 0.0 else s - hs**2 / (4.0 * h)
    if asym <= 0.0:
        # A negative leading coefficient is unbounded; an exactly flat
        # leading direction is a non-generic boundary requiring a separate
        # lower-degree analysis, so it is not certified as strictly BFB here.
        return False, float(asym), math.inf
    return bool(best[0] > 0.0), float(best[0]), float(best[1])


def threshold_match_below_radial(p: Dict[str, float], f: float) -> Dict[str, float]:
    """Leading tree-level zero-momentum matching after the heavy S radial mode."""
    if p["lamS"] <= 0.0:
        raise ValueError("lambda_S must be positive for radial matching")
    return {
        "m_radial_tree": math.sqrt(2.0 * p["lamS"]) * f,
        "lambdaH_low": p["lamH"] - p["lamHS"]**2 / (4.0 * p["lamS"]),
        "lambdac_low": p["lamc"] - p["lamSc"]**2 / (4.0 * p["lamS"]),
        "lambdaHc_low": p["lamHc"] - p["lamHS"] * p["lamSc"] / (2.0 * p["lamS"]),
        "mu3_coefficient_of_chi3_plus_hc": p["kappa"] * f / math.sqrt(2.0),
        "scope": "Tree-level zero-momentum matching; one-loop finite thresholds and higher-dimensional operators omitted.",
    }


def benchmark_initial() -> Dict[str, float]:
    return {
        "Gyy": 0.36, "Gyx": 0.0, "Gxy": 0.0, "Gxx": 0.10,
        "g2": 0.64, "g3": 1.05,
        "yt": 0.85, "yb": 0.015, "ytau": 0.010,
        "lamH": 0.13, "lamS": 0.30, "lamc": 0.25,
        "lamHS": 0.02, "lamHc": 0.05, "lamSc": 0.08, "kappa": 0.05,
        "mH2": -17867.08, "mS2": -300605.16, "mc2": 208487.10,
    }


def scalar_tensor_crosscheck() -> Dict[str, object]:
    scalar_tensor.build_potential()
    p = benchmark_initial()
    zero_gauge = p.copy()
    for key in ("Gyy", "Gyx", "Gxy", "Gxx", "g2", "g3", "yt", "yb", "ytau"):
        zero_gauge[key] = 0.0
    got = unpack(beta_numerator(pack(zero_gauge)))
    expected = {
        "lamH": 24*p["lamH"]**2+p["lamHS"]**2+p["lamHc"]**2,
        "lamS": 20*p["lamS"]**2+2*p["lamHS"]**2+p["lamSc"]**2,
        "lamc": 20*p["lamc"]**2+2*p["lamHc"]**2+p["lamSc"]**2+18*p["kappa"]**2,
        "lamHS": 12*p["lamH"]*p["lamHS"]+8*p["lamS"]*p["lamHS"]+4*p["lamHS"]**2+2*p["lamHc"]*p["lamSc"],
        "lamHc": 12*p["lamH"]*p["lamHc"]+8*p["lamc"]*p["lamHc"]+4*p["lamHc"]**2+2*p["lamHS"]*p["lamSc"],
        "lamSc": 8*p["lamS"]*p["lamSc"]+8*p["lamc"]*p["lamSc"]+4*p["lamSc"]**2+4*p["lamHS"]*p["lamHc"]+36*p["kappa"]**2,
        "kappa": p["kappa"]*(12*p["lamc"]+6*p["lamSc"]),
    }
    residuals = {key: got[key]-value for key, value in expected.items()}
    maximum = max(abs(x) for x in residuals.values())
    if maximum > 1e-13:
        raise RuntimeError(f"Scalar-tensor cross-check failed: {residuals}")
    return {"maximum_absolute_residual": maximum, "passed": True}


def run_benchmark(
    mu0: float = 1.0e3,
    mumax: float = 1.0e19,
    samples: int = 1200,
    rtol: float = 2e-10,
    atol: float = 1e-12,
    max_step: float = 0.05,
) -> Dict[str, object]:
    # Ensure imported use is identical to command-line use.  The builder is
    # idempotent, so this also prevents order-dependent validation results.
    scalar_tensor.build_potential()
    initial = benchmark_initial()
    y0 = pack(initial)
    t0, t1 = math.log(mu0), math.log(mumax)
    def perturbative_boundary(log_mu: float, values: np.ndarray) -> float:
        del log_mu
        # Quadratic masses are dimensionful and excluded from this criterion.
        return 4.0 * math.pi - float(np.max(np.abs(values[:-3])))

    perturbative_boundary.terminal = True
    perturbative_boundary.direction = -1
    solution = solve_ivp(
        beta, (t0, t1), y0, method="DOP853", rtol=rtol, atol=atol,
        dense_output=True, max_step=max_step, events=perturbative_boundary,
    )
    if not solution.success:
        raise RuntimeError(solution.message)
    actual_t1 = float(solution.t[-1])
    logs = np.linspace(t0, actual_t1, samples)
    trajectory = solution.sol(logs).T

    first_failure = None
    previous_safe_log = float(logs[0])
    minimum_bfb = {"margin": math.inf, "scale_GeV": None, "t": None}
    maximum_unitarity = {"spectral_radius": 0.0, "scale_GeV": None}
    maximum_coupling = {"absolute_value": 0.0, "name": None, "scale_GeV": None}
    scalar_names = ("lamH", "lamS", "lamc", "lamHS", "lamHc", "lamSc", "kappa")

    for logmu, row in zip(logs, trajectory):
        p = unpack(row)
        mu = math.exp(float(logmu))
        finite = all(math.isfinite(x) for x in row)
        bfb_ok, bfb_margin, bfb_t = exact_bfb_margin(p)
        quartics = {name: p[name] for name in scalar_names}
        rho = float(np.max(np.abs(unitarity_matrix.spectrum(quartics))))
        local_name = max(NAMES[:-3], key=lambda name: abs(p[name]))
        local_max = abs(p[local_name])
        perturbative = local_max < 4.0 * math.pi
        unitary = rho <= 8.0 * math.pi

        if bfb_margin < minimum_bfb["margin"]:
            minimum_bfb = {"margin": bfb_margin, "scale_GeV": mu, "t": bfb_t}
        if rho > maximum_unitarity["spectral_radius"]:
            maximum_unitarity = {"spectral_radius": rho, "scale_GeV": mu}
        if local_max > maximum_coupling["absolute_value"]:
            maximum_coupling = {"absolute_value": local_max, "name": local_name, "scale_GeV": mu}
        if first_failure is None and not (finite and bfb_ok and perturbative and unitary):
            reasons = []
            if not finite: reasons.append("nonfinite")
            if not bfb_ok: reasons.append("tree_BFB")
            if not perturbative: reasons.append("coupling_4pi")
            if not unitary: reasons.append("high_energy_scalar_unitarity")
            refined = None
            if reasons == ["high_energy_scalar_unitarity"] and logmu > previous_safe_log:
                def unitarity_excess(log_scale: float) -> float:
                    q = unpack(solution.sol(log_scale))
                    quartic_q = {name: q[name] for name in scalar_names}
                    return float(np.max(np.abs(unitarity_matrix.spectrum(quartic_q)))) - 8.0 * math.pi

                root = brentq(unitarity_excess, previous_safe_log, float(logmu), xtol=1e-12, rtol=1e-13)
                qroot = unpack(solution.sol(root))
                quartic_root = {name: qroot[name] for name in scalar_names}
                refined = {
                    "scale_GeV": math.exp(root),
                    "state": qroot,
                    "unitarity_spectral_radius": float(np.max(np.abs(unitarity_matrix.spectrum(quartic_root)))),
                    "root_method": "Brent bracketed solve in ln(mu)",
                }
            first_failure = {
                "first_failed_sample_scale_GeV": mu,
                "reasons": reasons,
                "state_at_failed_sample": p,
                "bfb_margin_at_failed_sample": bfb_margin,
                "unitarity_spectral_radius_at_failed_sample": rho,
                "refined_boundary": refined,
            }
            break
        previous_safe_log = float(logmu)

    final = unpack(trajectory[-1])
    mixing_abs = max(abs(final["Gyx"]), abs(final["Gxy"]))
    return {
        "status": "illustrative one-loop MS-bar evolution, not a precision fit",
        "mu0_GeV": mu0,
        "requested_mumax_GeV": mumax,
        "integration_end_GeV": math.exp(actual_t1),
        "stopped_at_perturbative_boundary": bool(solution.t_events[0].size),
        "samples": samples,
        "solver": {"method": "DOP853", "rtol": rtol, "atol": atol, "max_step_in_log_mu": max_step, "nfev": solution.nfev},
        "initial": initial,
        "tree_threshold_at_f_1000_GeV": threshold_match_below_radial(initial, 1000.0),
        "first_failure": first_failure,
        "minimum_bfb_before_failure": minimum_bfb,
        "maximum_unitarity_before_failure": maximum_unitarity,
        "maximum_dimensionless_coupling_before_failure": maximum_coupling,
        "final_state_at_integration_end": final,
        "zero_mixing_invariance_numerical_residual": mixing_abs,
        "scalar_tensor_crosscheck": scalar_tensor_crosscheck(),
        "scope_warnings": [
            "One-loop MS-bar running only; two-loop terms and finite one-loop threshold corrections are omitted.",
            "Tree-level BFB and high-energy scalar-unitarity tests are applied to running couplings; this is not a gauge-independent loop effective-potential analysis.",
            "Input SM couplings at 1 TeV are illustrative rounded values, not a precision pole-to-MS-bar match.",
            "The full 2x2 Abelian gauge matrix is implemented, but the benchmark starts on the zero-mixing trajectory.",
        ],
    }


def main() -> None:
    scalar_tensor.build_potential()
    result = run_benchmark()
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
